Admin/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace Admin.Controllers
{
    [ValidateInput(false)]
    public class CommentsController : BaseController
    {
        private emlakmvcContainer db = new emlakmvcContainer();

        // GET: Comments
        public ActionResult Index()
        {
            var commentSet = db.CommentSet.Include(c => c.User).Include(c => c.Ilan);
            return View(commentSet.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name");
            ViewBag.IlanId = new SelectList(db.IlanSet, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,IlanId,Text,Date,Verified")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.CommentSet.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", comment.UserId);
            ViewBag.IlanId = new SelectList(db.IlanSet, "Id", "Title", comment.IlanId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", comment.UserId);
            ViewBag.IlanId = new SelectList(db.IlanSet, "Id", "Title", comment.IlanId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,IlanId,Text,Date,Verified")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", comment.UserId);
            ViewBag.IlanId = new SelectList(db.IlanSet, "Id", "Title", comment.IlanId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.CommentSet.Find(id);
            db.CommentSet.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/Controllers/IlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Admin.Helpers;
using System.Drawing.Imaging;

namespace Admin.Controllers
{
    public class IlansController : BaseController
    {
        private emlakmvcContainer db = new emlakmvcContainer();

        // GET: Ilans
        public ActionResult Index()
        {
            var ilanSet = db.IlanSet.Include(i => i.Kategori).Include(i => i.IlanDetay).Include(i => i.User);
            return View(ilanSet.ToList());
        }

        // GET: Ilans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.IlanSet.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // GET: Ilans/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(db.KategoriSet, "Id", "KategoriAdi");
            ViewBag.IlanDetayId = new SelectList(db.IlanDetaySet, "Id", "Kat");
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name");
            return View();
        }

        // POST: Ilans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Fiyat,MetreKare,Tarih,UserId,KategoriId,IlanDetayId")] Ilan ilan , HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                if (Resim != null && Resim.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(Resim.InputStream))
                    {
                        ilan.Resim = reader.ReadBytes(Resim.ContentLength);
                    }
                }

                db.IlanSet.Add(ilan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriId = new SelectList(db.KategoriSet, "Id", "KategoriAdi", ilan.KategoriId);
            ViewBag.IlanDetayId = new SelectList(db.IlanDetaySet, "Id", "Kat", ilan.IlanDetayId);
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", ilan.UserId);
            return View(ilan);
        }

        // GET: Ilans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.IlanSet.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(db.KategoriSet, "Id", "KategoriAdi", ilan.KategoriId);
            ViewBag.IlanDetayId = new SelectList(db.IlanDetaySet, "Id", "Kat", ilan.IlanDetayId);
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", ilan.UserId);
            return View(ilan);
        }

        // POST: Ilans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Fiyat,MetreKare,Tarih,UserId,KategoriId,IlanDetayId")] Ilan ilan ,HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                if (Resim != null && Resim.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(Resim.InputStream))
                    {
                        ilan.Resim = reader.ReadBytes(Resim.ContentLength);
                    }
                }
                else
                {
                    db.Entry(ilan).Property("Resim").IsModified = false;
                }

                db.Entry(ilan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriId = new SelectList(db.KategoriSet, "Id", "KategoriAdi", ilan.KategoriId);
            ViewBag.IlanDetayId = new SelectList(db.IlanDetaySet, "Id", "Kat", ilan.IlanDetayId);
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Name", ilan.UserId);
            return View(ilan);
        }

        // GET: Ilans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.IlanSet.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // POST: Ilans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ilan ilan = db.IlanSet.Find(id);
            db.IlanSet.Remove(ilan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Resim(int id)
        {
            byte[] file = db.IlanSet.Find(id).Resim;
            if (file == null)
            {
                return Content("Resim bulunamadı");
            }
            return File(file, ImageHelper.GetContentType(file).ToString());
        }
    }
}

Admin/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace Admin.Controllers
{
    public class LogsController : BaseController
    {
        private emlakmvcContainer emlakmvc = new emlakmvcContainer();

        // GET: Logs
        public ActionResult Index()
        {
            var logSet = emlakmvc.LogSet.Include(l => l.User);
            return View(logSet.ToList());
        }

        // GET: Logs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = emlakmvc.LogSet.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                emlakmvc.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Admin.Helpers;
using System.Drawing.Imaging;

namespace Admin.Controllers
{
    public class UsersController : BaseController
    {
        private emlakmvcContainer db = new emlakmvcContainer();

        // GET: Users
        public ActionResult Index()
        {
            var userSet = db.UserSet.Include(u => u.UserType);
            return View(userSet.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.UserSet.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.UserTypeId = new SelectList(db.UserTypeSet, "Id", "Title");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserTypeId,Name,Mail,Telefon,Password")] User user,HttpPostedFileBase Avatar)
        {
            
                if (ModelState.IsValid)
            {
                if (Avatar != null && Avatar.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(Avatar.InputStream))
                    {
                        user.Avatar = reader.ReadBytes(Avatar.ContentLength);
                    }
                }
                db.UserSet.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserTypeId = new SelectList(db.UserTypeSet, "Id", "Title", user.UserTypeId);
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.UserSet.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserTypeId = new SelectList(db.UserTypeSet, "Id", "Title", user.UserTypeId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserTypeId,Name,Mail,Telefon,Password")] User user, HttpPostedFileBase Avatar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;

                if (Avatar != null && Avatar.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(Avatar.InputStream))
                    {
                        user.Avatar = reader.ReadBytes(Avatar.ContentLength);
                    }
                }
                else
                {
                    db.Entry(user).Property("Avatar").IsModified = false;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserTypeId = new SelectList(db.UserTypeSet, "Id", "Title", user.UserTypeId);
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.UserSet.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.UserSet.Find(id);
            db.UserSet.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Avatar(int id)
        {
            byte[] file = db.UserSet.Find(id).Avatar;
            if (file == null)
            {
                return Content("Resim bulunamadı");
            }
            return File(file, ImageHelper.GetContentType(file).ToString());
        }
    }
}

Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Admin Paneli";
}
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="row margin">
            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Ilans")">
                    <i class="fa fa-list-alt fa-3x"></i><br> <small>İlanlar</small>
                </a>
            </div>

            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","IlanDetays")">
                    <i class="fa fa-indent fa-3x"></i><br> <small>İlan Detayları</small>
                </a>
            </div>
            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Kategoris")">
                    <i class="fa fa-sliders fa-3x"></i><br> <small>Kategoriler</small>
                </a>
            </div>

            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index", "ProjectAccesses")">
                    <i class="fa fa-list fa-3x"></i><br> <small>Proje Erişimleri</small>
                </a>
            </div>
        </div>
        <br />
        <div class="row margin">
            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Projects")">
                    <i class="fa fa-database fa-3x"></i><br> <small>Projeler</small>
                </a>
            </div>
            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Payments")">
                    <i class="fa fa-credit-card fa-3x"></i><br> <small>Ödemeler</small>
                </a>
            </div>


            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Users")">
                    <i class="fa fa-user-circle fa-3x"></i><br> <small>Kullanıcılar</small>
                </a>
            </div>

            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","UserTypes")">
                    <i class="fa fa-users fa-3x"></i><br> <small>Kullanıcı Tipleri</small>
                </a>
            </div>
        </div>
        <br />
        <div class="row margin">
            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Comments")">
                    <i class="fa fa-weixin fa-3x"></i><br> <small>Yorumlar</small>
                </a>
            </div>

            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Sikayets")">
                    <i class="fa fa-warning fa-3x"></i><br> <small>Şikayetler</small>
                </a>
            </div>

            <div class="col-sm-3">
                <a class="btn btn-block btn-default" href="@Url.Action("Index","Logs")">
                    <i class="fa fa-area-chart fa-3x"></i><br> <small>İşlem Kayıtları</small>
                </a>
            </div>
        </div>
    </div>
       </div>
        
    

Admin/Views/Home/Login.cshtml
@{
    Layout = null;
    ViewBag.Title = "Login";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Emlak</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">
            <br />
            <div class="col-md-6 col-md-offset-3">
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger">@TempData["error"]</div>
                    <br />
                }
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-users fa-2x "> Giriş Yapın</i>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="post" action="@Url.Action("Login","Home")">
                            <div class="form-group">
                                <label for="email" class="col-sm-3 control-label fa fa-envelope fa-2x"></label>
                                <div class="col-sm-9">
                                    
                                    <input type="email" class="form-control" id="email" name="email" value="@Request.Form["Mail"]" placeholder="E-Posta">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="password" class="col-sm-3 control-label fa fa-key fa-2x"></label>
                                <div class="col-sm-9">
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Parola">
                                </div>
                            </div>
                            <div class="col-sm">
                                <button type="submit" class="btn btn-block">Giriş</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>